-- Auto-generated by scripts/generate_mf_coefs.py
-- DO NOT EDIT — regenerate with: python scripts/generate_mf_coefs.py
--
-- Matched filter coefficients: time-reversed, complex-conjugated chirp
-- in Q1.15 format. These are the FIR taps for the matched filter.

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

package mf_coef_pkg is

  constant MF_NUM_TAPS : integer := 64;

  type coef_array_type is array (0 to 63) of signed(15 downto 0);

  constant COEF_I : coef_array_type := (
       0 => to_signed(-27133, 16),  -- coef_i[0] = -0.828033
       1 => to_signed(-25202, 16),  -- coef_i[1] = -0.769104
       2 => to_signed( 13095, 16),  -- coef_i[2] = +0.399628
       3 => to_signed( 32522, 16),  -- coef_i[3] = +0.992493
       4 => to_signed(  5404, 16),  -- coef_i[4] = +0.164917
       5 => to_signed(-29448, 16),  -- coef_i[5] = -0.898682
       6 => to_signed(-22154, 16),  -- coef_i[6] = -0.676086
       7 => to_signed( 16846, 16),  -- coef_i[7] = +0.514099
       8 => to_signed( 31737, 16),  -- coef_i[8] = +0.968536
       9 => to_signed(  1407, 16),  -- coef_i[9] = +0.042938
      10 => to_signed(-30920, 16),  -- coef_i[10] = -0.943604
      11 => to_signed(-19195, 16),  -- coef_i[11] = -0.585785
      12 => to_signed( 19841, 16),  -- coef_i[12] = +0.605499
      13 => to_signed( 30784, 16),  -- coef_i[13] = +0.939453
      14 => to_signed( -1809, 16),  -- coef_i[14] = -0.055206
      15 => to_signed(-31834, 16),  -- coef_i[15] = -0.971497
      16 => to_signed(-16846, 16),  -- coef_i[16] = -0.514099
      17 => to_signed( 21856, 16),  -- coef_i[17] = +0.666992
      18 => to_signed( 29792, 16),  -- coef_i[18] = +0.909180
      19 => to_signed( -4211, 16),  -- coef_i[19] = -0.128510
      20 => to_signed(-32251, 16),  -- coef_i[20] = -0.984222
      21 => to_signed(-15091, 16),  -- coef_i[21] = -0.460541
      22 => to_signed( 23170, 16),  -- coef_i[22] = +0.707092
      23 => to_signed( 28993, 16),  -- coef_i[23] = +0.884796
      24 => to_signed( -5800, 16),  -- coef_i[24] = -0.177002
      25 => to_signed(-32470, 16),  -- coef_i[25] = -0.990906
      26 => to_signed(-14010, 16),  -- coef_i[26] = -0.427551
      27 => to_signed( 24008, 16),  -- coef_i[27] = +0.732666
      28 => to_signed( 28610, 16),  -- coef_i[28] = +0.873108
      29 => to_signed( -6393, 16),  -- coef_i[29] = -0.195099
      30 => to_signed(-32546, 16),  -- coef_i[30] = -0.993225
      31 => to_signed(-13646, 16),  -- coef_i[31] = -0.416443
      32 => to_signed( 24144, 16),  -- coef_i[32] = +0.736816
      33 => to_signed( 28610, 16),  -- coef_i[33] = +0.873108
      34 => to_signed( -6393, 16),  -- coef_i[34] = -0.195099
      35 => to_signed(-32522, 16),  -- coef_i[35] = -0.992493
      36 => to_signed(-14010, 16),  -- coef_i[36] = -0.427551
      37 => to_signed( 23732, 16),  -- coef_i[37] = +0.724243
      38 => to_signed( 28899, 16),  -- coef_i[38] = +0.881927
      39 => to_signed( -5404, 16),  -- coef_i[39] = -0.164917
      40 => to_signed(-32383, 16),  -- coef_i[40] = -0.988251
      41 => to_signed(-15091, 16),  -- coef_i[41] = -0.460541
      42 => to_signed( 22740, 16),  -- coef_i[42] = +0.693970
      43 => to_signed( 29622, 16),  -- coef_i[43] = +0.903992
      44 => to_signed( -3812, 16),  -- coef_i[44] = -0.116333
      45 => to_signed(-32015, 16),  -- coef_i[45] = -0.977020
      46 => to_signed(-16846, 16),  -- coef_i[46] = -0.514099
      47 => to_signed( 21097, 16),  -- coef_i[47] = +0.643829
      48 => to_signed( 30572, 16),  -- coef_i[48] = +0.932983
      49 => to_signed( -1206, 16),  -- coef_i[49] = -0.036804
      50 => to_signed(-31357, 16),  -- coef_i[50] = -0.956940
      51 => to_signed(-19195, 16),  -- coef_i[51] = -0.585785
      52 => to_signed( 18703, 16),  -- coef_i[52] = +0.570770
      53 => to_signed( 31581, 16),  -- coef_i[53] = +0.963776
      54 => to_signed(  2009, 16),  -- coef_i[54] = +0.061310
      55 => to_signed(-30196, 16),  -- coef_i[55] = -0.921509
      56 => to_signed(-22154, 16),  -- coef_i[56] = -0.676086
      57 => to_signed( 15447, 16),  -- coef_i[57] = +0.471405
      58 => to_signed( 32413, 16),  -- coef_i[58] = +0.989166
      59 => to_signed(  6195, 16),  -- coef_i[59] = +0.189056
      60 => to_signed(-28209, 16),  -- coef_i[60] = -0.860870
      61 => to_signed(-25202, 16),  -- coef_i[61] = -0.769104
      62 => to_signed( 11228, 16),  -- coef_i[62] = +0.342651
      63 => to_signed( 32767, 16)   -- coef_i[63] = +0.999969
  );

  constant COEF_Q : coef_array_type := (
       0 => to_signed( 18372, 16),  -- coef_q[0] = +0.560669
       1 => to_signed(-20943, 16),  -- coef_q[1] = -0.639130
       2 => to_signed(-30038, 16),  -- coef_q[2] = -0.916687
       3 => to_signed(  4011, 16),  -- coef_q[3] = +0.122406
       4 => to_signed( 32319, 16),  -- coef_q[4] = +0.986298
       5 => to_signed( 14373, 16),  -- coef_q[5] = +0.438629
       6 => to_signed(-24144, 16),  -- coef_q[6] = -0.736816
       7 => to_signed(-28106, 16),  -- coef_q[7] = -0.857727
       8 => to_signed(  8157, 16),  -- coef_q[8] = +0.248932
       9 => to_signed( 32738, 16),  -- coef_q[9] = +0.999084
      10 => to_signed( 10850, 16),  -- coef_q[10] = +0.331116
      11 => to_signed(-26557, 16),  -- coef_q[11] = -0.810455
      12 => to_signed(-26078, 16),  -- coef_q[12] = -0.795837
      13 => to_signed( 11228, 16),  -- coef_q[13] = +0.342651
      14 => to_signed( 32718, 16),  -- coef_q[14] = +0.998474
      15 => to_signed(  7767, 16),  -- coef_q[15] = +0.237030
      16 => to_signed(-28106, 16),  -- coef_q[16] = -0.857727
      17 => to_signed(-24414, 16),  -- coef_q[17] = -0.745056
      18 => to_signed( 13646, 16),  -- coef_q[18] = +0.416443
      19 => to_signed( 32496, 16),  -- coef_q[19] = +0.991699
      20 => to_signed(  5800, 16),  -- coef_q[20] = +0.177002
      21 => to_signed(-29086, 16),  -- coef_q[21] = -0.887634
      22 => to_signed(-23170, 16),  -- coef_q[22] = -0.707092
      23 => to_signed( 15269, 16),  -- coef_q[23] = +0.465973
      24 => to_signed( 32251, 16),  -- coef_q[24] = +0.984222
      25 => to_signed(  4410, 16),  -- coef_q[25] = +0.134583
      26 => to_signed(-29622, 16),  -- coef_q[26] = -0.903992
      27 => to_signed(-22302, 16),  -- coef_q[27] = -0.680603
      28 => to_signed( 15976, 16),  -- coef_q[28] = +0.487549
      29 => to_signed( 32138, 16),  -- coef_q[29] = +0.980774
      30 => to_signed(  3812, 16),  -- coef_q[30] = +0.116333
      31 => to_signed(-29792, 16),  -- coef_q[31] = -0.909180
      32 => to_signed(-22154, 16),  -- coef_q[32] = -0.676086
      33 => to_signed( 15976, 16),  -- coef_q[33] = +0.487549
      34 => to_signed( 32138, 16),  -- coef_q[34] = +0.980774
      35 => to_signed(  4011, 16),  -- coef_q[35] = +0.122406
      36 => to_signed(-29622, 16),  -- coef_q[36] = -0.903992
      37 => to_signed(-22595, 16),  -- coef_q[37] = -0.689545
      38 => to_signed( 15447, 16),  -- coef_q[38] = +0.471405
      39 => to_signed( 32319, 16),  -- coef_q[39] = +0.986298
      40 => to_signed(  5007, 16),  -- coef_q[40] = +0.152802
      41 => to_signed(-29086, 16),  -- coef_q[41] = -0.887634
      42 => to_signed(-23593, 16),  -- coef_q[42] = -0.720001
      43 => to_signed( 14010, 16),  -- coef_q[43] = +0.427551
      44 => to_signed( 32546, 16),  -- coef_q[44] = +0.993225
      45 => to_signed(  6983, 16),  -- coef_q[45] = +0.213104
      46 => to_signed(-28106, 16),  -- coef_q[46] = -0.857727
      47 => to_signed(-25073, 16),  -- coef_q[47] = -0.765167
      48 => to_signed( 11793, 16),  -- coef_q[48] = +0.359894
      49 => to_signed( 32746, 16),  -- coef_q[49] = +0.999329
      50 => to_signed(  9512, 16),  -- coef_q[50] = +0.290283
      51 => to_signed(-26557, 16),  -- coef_q[51] = -0.810455
      52 => to_signed(-26906, 16),  -- coef_q[52] = -0.821106
      53 => to_signed(  8740, 16),  -- coef_q[53] = +0.266724
      54 => to_signed( 32706, 16),  -- coef_q[54] = +0.998108
      55 => to_signed( 12725, 16),  -- coef_q[55] = +0.388336
      56 => to_signed(-24144, 16),  -- coef_q[56] = -0.736816
      57 => to_signed(-28899, 16),  -- coef_q[57] = -0.881927
      58 => to_signed(  4808, 16),  -- coef_q[58] = +0.146729
      59 => to_signed( 32177, 16),  -- coef_q[59] = +0.981964
      60 => to_signed( 16673, 16),  -- coef_q[60] = +0.508820
      61 => to_signed(-20943, 16),  -- coef_q[61] = -0.639130
      62 => to_signed(-30784, 16),  -- coef_q[62] = -0.939453
      63 => to_signed(     0, 16)   -- coef_q[63] = +0.000000
  );

end package mf_coef_pkg;
