"""
Generate a VHDL package containing a 1024-entry Q1.15 sine lookup table.

The table covers one full cycle of sin(2π * i / 1024) for i in [0, 1023].
Cosine is obtained by offsetting the index by 256 (quarter cycle):
    cos(x) = sin_table((index + 256) mod 1024)

Output: rtl/common/sin_lut_pkg.vhd

Run:
    python scripts/generate_sin_lut.py
"""

import os
import math
import numpy as np

# --- Parameters ---
TABLE_SIZE = 1024       # number of entries (must be a power of 2)
SAMPLE_BITS = 16        # Q1.15 output width
FRAC_BITS = 15
SCALE = 2 ** FRAC_BITS  # 32768
MAX_VAL = SCALE - 1     # 32767
MIN_VAL = -SCALE        # -32768

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'rtl', 'common')
OUTPUT_FILE = os.path.join(OUTPUT_DIR, 'sin_lut_pkg.vhd')


def float_to_q15(x):
    """Convert a float in [-1, 1) to a Q1.15 integer, with saturation."""
    raw = int(round(x * SCALE))
    return max(MIN_VAL, min(MAX_VAL, raw))


def generate_table():
    """Compute 1024 Q1.15 sine values."""
    table = []
    for i in range(TABLE_SIZE):
        angle = 2.0 * math.pi * i / TABLE_SIZE
        table.append(float_to_q15(math.sin(angle)))
    return table


def write_vhdl(table):
    """Write the sine table as a VHDL package with a constant array."""
    index_bits = int(math.log2(TABLE_SIZE))  # 10 for 1024

    lines = []
    lines.append('-- Auto-generated by scripts/generate_sin_lut.py')
    lines.append('-- DO NOT EDIT — regenerate with: python scripts/generate_sin_lut.py')
    lines.append('')
    lines.append('library IEEE;')
    lines.append('use IEEE.std_logic_1164.all;')
    lines.append('use IEEE.numeric_std.all;')
    lines.append('')
    lines.append('package sin_lut_pkg is')
    lines.append('')
    lines.append(f'  constant LUT_INDEX_BITS : integer := {index_bits};')
    lines.append(f'  constant LUT_SIZE       : integer := {TABLE_SIZE};')
    lines.append(f'  constant LUT_QUARTER    : integer := {TABLE_SIZE // 4};')
    lines.append('')
    lines.append(f'  type sin_lut_type is array (0 to {TABLE_SIZE - 1})'
                 f' of signed({SAMPLE_BITS - 1} downto 0);')
    lines.append('')
    lines.append('  constant SIN_TABLE : sin_lut_type := (')

    for i, val in enumerate(table):
        comma = ',' if i < TABLE_SIZE - 1 else ' '
        # Show the float equivalent as a comment for readability
        float_val = val / SCALE
        lines.append(f'    {i:4d} => to_signed({val:6d}, {SAMPLE_BITS}){comma}'
                     f'  -- sin(2pi*{i}/1024) = {float_val:+.6f}')

    lines.append('  );')
    lines.append('')
    lines.append('end package sin_lut_pkg;')
    lines.append('')

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(OUTPUT_FILE, 'w') as f:
        f.write('\n'.join(lines))

    print(f'Generated {OUTPUT_FILE}')
    print(f'  Table size:  {TABLE_SIZE} entries')
    print(f'  Index bits:  {index_bits}')
    print(f'  Sample bits: {SAMPLE_BITS} (Q1.{FRAC_BITS})')
    print(f'  Range:       [{table[0]}, {max(table)}] -> '
          f'[{table[0]/SCALE:.6f}, {max(table)/SCALE:.6f}]')


if __name__ == '__main__':
    table = generate_table()
    write_vhdl(table)
