"""
Generate CFAR detector test vectors for VHDL simulation.

Creates two files:
  - rtl/common/cfar_input.csv    — input I/Q samples (32-bit signed, matched
                                    filter output format, signed decimal)
  - rtl/common/cfar_expected.csv — expected detection flag per sample
                                    (0 or 1, one per line)

The input is generated by running:
    chirp -> simulated received signal -> matched filter (fixed-point)
and then captured as if it came from the matched filter.

The expected output is computed by a Python reference that replicates the
VHDL CFAR detector's exact fixed-point math.

Run:
    python scripts/generate_cfar_test_vectors.py
"""

import os
import math
import numpy as np

# --- Parameters (must match VHDL generics) ---
SAMPLE_RATE = 200_000
F_START     = 39_000
F_END       = 41_000
NUM_SAMPLES = 64
PHASE_WIDTH = 24
FRAC_BITS   = 15
Q15_SCALE   = 2 ** FRAC_BITS
Q15_MAX     = Q15_SCALE - 1
Q15_MIN     = -Q15_SCALE
LUT_SIZE    = 1024
LUT_QUARTER = 256

# Matched filter output is 32-bit signed
MF_OUTPUT_WIDTH = 32

# CFAR parameters (must match cfar_detector.vhd generics)
NUM_TRAIN     = 64
NUM_GUARD     = 32
ALPHA_Q       = 3949              # Q16.16 of (7.71 / (2*NUM_TRAIN)) — bakes the training-average divide into alpha
INPUT_SHIFT   = 12
MAG_WIDTH     = 40

WINDOW_SIZE   = 2 * (NUM_TRAIN + NUM_GUARD) + 1   # 193

# Test scenario
# Targets placed well after the CFAR warmup region (WINDOW_SIZE = 193)
TARGET_DELAYS     = [300, 500, 700]
TARGET_AMPLITUDES = [1.0, 0.7, 0.5]
NOISE_POWER       = 0.01
TOTAL_LENGTH      = 1000
RANDOM_SEED       = 42

OUTPUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'rtl', 'common')


# ===================================================================
# Chirp / matched filter / received signal generation
# (copied from generate_mf_test_vectors.py so we produce the same inputs)
# ===================================================================

def float_to_q15(x):
    raw = int(round(x * Q15_SCALE))
    return max(Q15_MIN, min(Q15_MAX, raw))


def build_sin_table():
    return [float_to_q15(math.sin(2.0 * math.pi * i / LUT_SIZE))
            for i in range(LUT_SIZE)]


def generate_chirp_q15():
    sin_table = build_sin_table()
    fcw_start = int(round(F_START * (2 ** PHASE_WIDTH) / SAMPLE_RATE))
    fcw_end   = int(round(F_END   * (2 ** PHASE_WIDTH) / SAMPLE_RATE))
    fcw_step  = (fcw_end - fcw_start) // (NUM_SAMPLES - 1)
    phase_mask = (1 << PHASE_WIDTH) - 1
    lut_shift  = PHASE_WIDTH - 10

    phase, fcw = 0, fcw_start
    chirp_i, chirp_q = [], []
    for n in range(NUM_SAMPLES):
        lut_index = (phase >> lut_shift) & (LUT_SIZE - 1)
        cos_index = (lut_index + LUT_QUARTER) % LUT_SIZE
        chirp_i.append(sin_table[cos_index])
        chirp_q.append(sin_table[lut_index])
        phase = (phase + fcw) & phase_mask
        fcw += fcw_step
    return chirp_i, chirp_q


def simulate_received_q15(chirp_i, chirp_q):
    np.random.seed(RANDOM_SEED)
    noise_sigma = math.sqrt(NOISE_POWER / 2.0)
    rx_float_i = noise_sigma * np.random.randn(TOTAL_LENGTH)
    rx_float_q = noise_sigma * np.random.randn(TOTAL_LENGTH)

    for delay, amp in zip(TARGET_DELAYS, TARGET_AMPLITUDES):
        for n in range(NUM_SAMPLES):
            idx = delay + n
            if idx >= TOTAL_LENGTH:
                break
            rx_float_i[idx] += amp * chirp_i[n] / Q15_SCALE
            rx_float_q[idx] += amp * chirp_q[n] / Q15_SCALE

    return ([float_to_q15(x) for x in rx_float_i],
            [float_to_q15(x) for x in rx_float_q])


def matched_filter_fixed(rx_i, rx_q, chirp_i, chirp_q):
    """Same implementation as in generate_mf_test_vectors.py."""
    num_taps = len(chirp_i)
    coef_i = list(reversed(chirp_i))
    coef_q = [-q for q in reversed(chirp_q)]

    buf_i = [0] * num_taps
    buf_q = [0] * num_taps
    out_i, out_q = [], []

    max32 = (1 << 31) - 1
    min32 = -(1 << 31)

    for n in range(len(rx_i)):
        for k in range(num_taps - 1, 0, -1):
            buf_i[k] = buf_i[k - 1]
            buf_q[k] = buf_q[k - 1]
        buf_i[0] = rx_i[n]
        buf_q[0] = rx_q[n]

        accum_real = 0
        accum_imag = 0
        for k in range(num_taps):
            accum_real += buf_i[k] * coef_i[k] - buf_q[k] * coef_q[k]
            accum_imag += buf_i[k] * coef_q[k] + buf_q[k] * coef_i[k]

        real_trunc = max(min32, min(max32, accum_real >> 16))
        imag_trunc = max(min32, min(max32, accum_imag >> 16))
        out_i.append(real_trunc)
        out_q.append(imag_trunc)

    return out_i, out_q


# ===================================================================
# CFAR reference — matches cfar_detector.vhd exactly
# ===================================================================

def cfar_fixed(mf_i, mf_q):
    """
    Python reference matching the VHDL CFAR detector bit-exactly.

    Inputs: matched filter output I/Q as 32-bit signed integers.
    Output: detection flag (0 or 1) per sample, same length as input.

    Replicates the VHDL logic:
      - Shift I/Q right by INPUT_SHIFT to 20 bits
      - Magnitude squared = shifted_i**2 + shifted_q**2 (40-bit unsigned)
      - Sliding window of WINDOW_SIZE magnitudes
      - Running sums on left and right training regions
      - Threshold = ((sum_left + sum_right) * ALPHA_Q) >> 16
      - CUT is at index (NUM_TRAIN + NUM_GUARD - 1) (the value about
        to shift into the CUT position)
      - Output 0 during warmup, then detection decisions
    """
    mag_buffer = [0] * WINDOW_SIZE
    sum_left   = 0
    sum_right  = 0
    warmup     = 0
    window_full = False

    detections = []

    for sample_i, sample_q in zip(mf_i, mf_q):
        # Truncate the 32-bit signed input to 20 bits by right-shifting.
        # This models VHDL's `s_axis_tdata_i(31 downto INPUT_SHIFT)`.
        shifted_i = sample_i >> INPUT_SHIFT
        shifted_q = sample_q >> INPUT_SHIFT

        # Magnitude squared (unsigned 40-bit)
        new_mag = (shifted_i * shifted_i + shifted_q * shifted_q) & ((1 << MAG_WIDTH) - 1)

        # Running sum updates (read pre-shift values)
        # Right training:
        #   + new_mag (entering at position 0)
        #   - mag_buffer[NUM_TRAIN - 1] (leaving right training as it shifts into right guard)
        sum_right += new_mag - mag_buffer[NUM_TRAIN - 1]

        # Left training:
        #   + mag_buffer[NUM_TRAIN + 2*NUM_GUARD] (entering left training from left guard)
        #   - mag_buffer[WINDOW_SIZE - 1] (oldest sample falling off)
        sum_left += mag_buffer[NUM_TRAIN + 2 * NUM_GUARD] - mag_buffer[WINDOW_SIZE - 1]

        # Shift the buffer (move [k-1] -> [k])
        for k in range(WINDOW_SIZE - 1, 0, -1):
            mag_buffer[k] = mag_buffer[k - 1]
        mag_buffer[0] = new_mag

        # Warmup counter
        if warmup == WINDOW_SIZE - 1:
            window_full = True
        else:
            warmup += 1

        # Detection (note: use pre-shift values, matching the VHDL which
        # reads mag_buffer during the same clock as the shift — VHDL signal
        # semantics mean reads see the pre-update value)
        if window_full:
            total_sum = sum_left + sum_right
            threshold = (total_sum * ALPHA_Q) >> 16
            # CUT is the value about to become the CUT (pre-shift, at index
            # NUM_TRAIN + NUM_GUARD - 1)
            # After our buffer update above, we already shifted, so we need
            # to re-read the correct pre-shift index.
            # Simplest: save cut_value before the shift.
            # To do that properly, we redo the order below.
            pass
        # Placeholder — we'll rework with correct ordering below
        detections.append(0)

    return detections


def cfar_fixed_v2(mf_i, mf_q):
    """
    Proper ordering: capture CUT value BEFORE the shift, so index semantics
    match the VHDL (which reads mag_buffer[...] in the same clocked block
    where it also assigns mag_buffer — reads see pre-shift values).
    """
    mag_buffer = [0] * WINDOW_SIZE
    sum_left   = 0
    sum_right  = 0
    warmup     = 0
    window_full = False

    detections = []

    mag_mask = (1 << MAG_WIDTH) - 1

    for sample_i, sample_q in zip(mf_i, mf_q):
        shifted_i = sample_i >> INPUT_SHIFT
        shifted_q = sample_q >> INPUT_SHIFT
        new_mag = (shifted_i * shifted_i + shifted_q * shifted_q) & mag_mask

        # Pre-shift reads (VHDL signal semantics)
        leaving_right = mag_buffer[NUM_TRAIN - 1]
        entering_left = mag_buffer[NUM_TRAIN + 2 * NUM_GUARD]
        leaving_left  = mag_buffer[WINDOW_SIZE - 1]
        cut_value     = mag_buffer[NUM_TRAIN + NUM_GUARD - 1]

        # Compute new running sums
        new_sum_right = sum_right + new_mag - leaving_right
        new_sum_left  = sum_left + entering_left - leaving_left

        # Detection decision (uses CURRENT sums, from previous clock)
        # VHDL reads sum_left/sum_right here as signals, getting their
        # pre-update values. This matches the VHDL behavior exactly.
        if window_full:
            total_sum = sum_left + sum_right
            threshold = (total_sum * ALPHA_Q) >> 16
            detection = 1 if cut_value > threshold else 0
        else:
            detection = 0
        detections.append(detection)

        # Commit the new values (simulating next-clock signal updates)
        sum_right = new_sum_right
        sum_left  = new_sum_left

        for k in range(WINDOW_SIZE - 1, 0, -1):
            mag_buffer[k] = mag_buffer[k - 1]
        mag_buffer[0] = new_mag

        if warmup == WINDOW_SIZE - 1:
            window_full = True
        else:
            warmup += 1

    return detections


# ===================================================================
# Main
# ===================================================================

def main():
    print('Generating chirp...')
    chirp_i, chirp_q = generate_chirp_q15()

    print(f'Simulating received signal ({TOTAL_LENGTH} samples)...')
    rx_i, rx_q = simulate_received_q15(chirp_i, chirp_q)

    print('Running matched filter (fixed-point)...')
    mf_i, mf_q = matched_filter_fixed(rx_i, rx_q, chirp_i, chirp_q)

    print('Running CFAR (fixed-point Python reference)...')
    detections = cfar_fixed_v2(mf_i, mf_q)

    # Write input CSV (matched filter output → CFAR input)
    input_path = os.path.join(OUTPUT_DIR, 'cfar_input.csv')
    with open(input_path, 'w') as f:
        for i_val, q_val in zip(mf_i, mf_q):
            f.write(f'{i_val},{q_val}\n')
    print(f'Wrote {len(mf_i)} input samples to {input_path}')

    # Write expected output CSV (one detection flag per line)
    expected_path = os.path.join(OUTPUT_DIR, 'cfar_expected.csv')
    with open(expected_path, 'w') as f:
        for d in detections:
            f.write(f'{d}\n')
    print(f'Wrote {len(detections)} detection flags to {expected_path}')

    # Quick summary
    n_detects = sum(detections)
    detect_indices = [i for i, d in enumerate(detections) if d == 1]
    print()
    print(f'Total detections: {n_detects}')
    print(f'Detection indices: {detect_indices[:20]}'
          + (' ...' if len(detect_indices) > 20 else ''))


if __name__ == '__main__':
    main()
