"""
Generate a VHDL package containing matched filter coefficients.

The coefficients are the time-reversed, complex-conjugated chirp
quantized to Q1.15. These are the FIR taps for the matched filter.

  coef[k] = conj(chirp[N-1-k])

Since conj(a + jb) = a - jb, the real part stays the same and the
imaginary part gets its sign flipped.

Output: rtl/common/mf_coef_pkg.vhd

Run:
    python scripts/generate_mf_coefs.py
"""

import os
import math

# --- Parameters (must match chirp.vhd generics) ---
SAMPLE_RATE = 200_000
F_START     = 39_000
F_END       = 41_000
NUM_SAMPLES = 64
PHASE_WIDTH = 24
FRAC_BITS   = 15
SCALE       = 2 ** FRAC_BITS
MAX_VAL     = SCALE - 1
MIN_VAL     = -SCALE
LUT_SIZE    = 1024
LUT_QUARTER = 256

OUTPUT_DIR  = os.path.join(os.path.dirname(__file__), '..', 'rtl', 'common')
OUTPUT_FILE = os.path.join(OUTPUT_DIR, 'mf_coef_pkg.vhd')


def float_to_q15(x):
    raw = int(round(x * SCALE))
    return max(MIN_VAL, min(MAX_VAL, raw))


def build_sin_table():
    table = []
    for i in range(LUT_SIZE):
        angle = 2.0 * math.pi * i / LUT_SIZE
        table.append(float_to_q15(math.sin(angle)))
    return table


def generate_chirp_q15():
    """Reproduce the exact DDS logic from chirp.vhd to get the chirp
    samples in Q1.15, then reverse and conjugate them."""
    sin_table = build_sin_table()

    fcw_start = int(round(F_START * (2 ** PHASE_WIDTH) / SAMPLE_RATE))
    fcw_end   = int(round(F_END   * (2 ** PHASE_WIDTH) / SAMPLE_RATE))
    fcw_step  = (fcw_end - fcw_start) // (NUM_SAMPLES - 1)

    phase_mask = (1 << PHASE_WIDTH) - 1
    lut_shift  = PHASE_WIDTH - 10

    phase = 0
    fcw = fcw_start
    chirp_i = []
    chirp_q = []

    for n in range(NUM_SAMPLES):
        lut_index = (phase >> lut_shift) & (LUT_SIZE - 1)
        cos_index = (lut_index + LUT_QUARTER) % LUT_SIZE
        chirp_i.append(sin_table[cos_index])
        chirp_q.append(sin_table[lut_index])
        phase = (phase + fcw) & phase_mask
        fcw = fcw + fcw_step

    # Matched filter coefficients: time-reversed, complex-conjugated.
    # Reverse: coef[k] = chirp[N-1-k]
    # Conjugate: flip sign of imaginary part
    coef_i = list(reversed(chirp_i))         # real stays the same
    coef_q = [-q for q in reversed(chirp_q)] # imag sign flipped

    return coef_i, coef_q


def write_vhdl(coef_i, coef_q):
    num_taps = len(coef_i)

    lines = []
    lines.append('-- Auto-generated by scripts/generate_mf_coefs.py')
    lines.append('-- DO NOT EDIT — regenerate with: python scripts/generate_mf_coefs.py')
    lines.append('--')
    lines.append('-- Matched filter coefficients: time-reversed, complex-conjugated chirp')
    lines.append('-- in Q1.15 format. These are the FIR taps for the matched filter.')
    lines.append('')
    lines.append('library IEEE;')
    lines.append('use IEEE.std_logic_1164.all;')
    lines.append('use IEEE.numeric_std.all;')
    lines.append('')
    lines.append('package mf_coef_pkg is')
    lines.append('')
    lines.append(f'  constant MF_NUM_TAPS : integer := {num_taps};')
    lines.append('')
    lines.append(f'  type coef_array_type is array (0 to {num_taps - 1})'
                 f' of signed(15 downto 0);')
    lines.append('')

    # Real coefficients
    lines.append('  constant COEF_I : coef_array_type := (')
    for k, val in enumerate(coef_i):
        comma = ',' if k < num_taps - 1 else ' '
        float_val = val / SCALE
        lines.append(f'    {k:4d} => to_signed({val:6d}, 16){comma}'
                     f'  -- coef_i[{k}] = {float_val:+.6f}')
    lines.append('  );')
    lines.append('')

    # Imaginary coefficients
    lines.append('  constant COEF_Q : coef_array_type := (')
    for k, val in enumerate(coef_q):
        comma = ',' if k < num_taps - 1 else ' '
        float_val = val / SCALE
        lines.append(f'    {k:4d} => to_signed({val:6d}, 16){comma}'
                     f'  -- coef_q[{k}] = {float_val:+.6f}')
    lines.append('  );')
    lines.append('')
    lines.append('end package mf_coef_pkg;')
    lines.append('')

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with open(OUTPUT_FILE, 'w') as f:
        f.write('\n'.join(lines))

    print(f'Generated {OUTPUT_FILE}')
    print(f'  Number of taps: {num_taps}')
    print(f'  Coef I range:   [{min(coef_i)}, {max(coef_i)}]')
    print(f'  Coef Q range:   [{min(coef_q)}, {max(coef_q)}]')


if __name__ == '__main__':
    coef_i, coef_q = generate_chirp_q15()
    write_vhdl(coef_i, coef_q)
